version: "3.9"
services:
  server:
    build:  ./flask-server
    volumes: 
    - ./flask-server:/app
    deploy:
      replicas: 5

  loadbalancer:
    image: 'dockercloud/haproxy:latest'
    links:
      - server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
  web:
    build: ./client/
    ports: 
      - "3001:3000"
    depends_on: 
      - server
    links:
      - loadbalancer

# Clean cache and rebuild all resources:
# docker-compose rm -f
# docker-compose pull
# docker-compose up --build -d